"""pr node — push the migration branch and open a GitHub PR.

HITL gate 3: interrupt_before=["pr"] in graph.compile(). The human sees
applied_patches + gave_up_files in the state, reviews, then resumes.
This node runs once on resume and opens the PR.
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
import uuid
from pathlib import Path

from agent_core.models import Tier, complete_with_cost, get_run_budget
from agent_core.tracing import flush as langfuse_flush, get_trace_url, init_trace, log_span
from migration.profiles import load_profile
from migration.state import MigrationState

log = logging.getLogger(__name__)

_PR_BODY_FALLBACK = """\
## Automated `{profile_name}` migration

Generated by **code-migration-agent**.

| | |
|---|---|
| Profile | `{profile_name}` |
| Files migrated | {files_ok} |
| Files skipped | {files_skipped} |
| Estimated cost | ${cost:.4f} USD |

### Files changed
{file_list}

### Skipped (manual attention needed)
{skipped_list}

---
*Trace: {trace_url}*
"""

_PR_BODY_LLM_SYSTEM = """\
You are a senior engineer writing a pull request description for an automated code migration.
Write a clear, concise PR body in GitHub-flavoured markdown. Include:

1. **What was migrated** — a brief paragraph describing the scope and goal
2. **Patterns applied** — bullet list of the main transformation patterns used
3. **Things to watch out for** — any gotchas, complex changes, or files that needed extra fix attempts
4. **Manual review needed** — files that the agent gave up on, and why they need human attention
5. **Testing notes** — how to verify the migration is correct

Be specific and actionable. Avoid generic filler sentences.
"""

_PR_BODY_LLM_PROMPT = """\
Migration profile: {profile_name}
Files migrated ({files_ok}):
{file_rules_list}

Files skipped / gave up ({files_skipped}):
{skipped_detail}

Critic notes (flags raised during review):
{critic_notes}

User feedback (if any):
{user_pr_feedback}

LLM cost: ${cost:.4f} USD
Trace: {trace_url}

Write the PR description now.
"""


def pr(state: MigrationState) -> MigrationState:
    """Push the branch and open a GitHub PR.

    Called once after HITL gate 3 approves (the static interrupt fires
    *before* this node; on resume this runs to completion).
    """
    applied_patches = state.get("applied_patches", [])
    gave_up_files = state.get("gave_up_files", [])
    profile_name = state.get("profile_name", "")
    repo_path = Path(state.get("repo_path", ""))
    repo_url = state.get("repo_url", "")

    # Resolve Langfuse trace URL (no-op if tracing not configured)
    run_id = state.get("run_id", "default")
    trace = init_trace(run_id, f"{profile_name} migration")
    trace_url = get_trace_url(trace)
    log_span(trace, "pr", input_data={"files_ok": len(applied_patches), "gave_up": len(gave_up_files)})

    if not applied_patches:
        log.warning("No patches to commit — nothing to push")
        langfuse_flush()
        return {**state, "pr_url": "(no changes)", "langfuse_trace_url": trace_url}

    github_token = os.environ.get("GITHUB_TOKEN", "")
    if not github_token:
        log.warning("GITHUB_TOKEN not set — skipping push/PR")
        langfuse_flush()
        return {**state, "pr_url": "(no GITHUB_TOKEN)", "langfuse_trace_url": trace_url}

    # Create and push the migration branch
    branch = f"migration/{profile_name}/{uuid.uuid4().hex[:8]}"
    _git_checkout_branch(repo_path, branch)

    # All commits were made by next_file; we just need to push the branch
    _git_push(repo_path, branch, repo_url, github_token)

    # Generate PR body (LLM-authored, falls back to template)
    pr_body = _generate_pr_body_llm(
        profile_name=profile_name,
        applied_patches=applied_patches,
        gave_up_files=gave_up_files,
        file_eval_records=state.get("file_eval_records", []),
        cost=state.get("total_cost_usd", 0.0),
        trace_url=trace_url,
        user_pr_feedback=state.get("user_pr_feedback", ""),
        run_id=state.get("run_id", "default"),
    )

    # Open PR via PyGithub
    pr_url = _open_github_pr(
        repo_url=repo_url,
        branch=branch,
        profile_name=profile_name,
        applied_patches=applied_patches,
        gave_up_files=gave_up_files,
        cost=state.get("total_cost_usd", 0.0),
        github_token=github_token,
        pr_body=pr_body,
    )

    log.info("PR opened: %s", pr_url)
    _teardown_sandbox(state)
    langfuse_flush()
    return {**state, "pr_url": pr_url, "langfuse_trace_url": trace_url}


def _git_checkout_branch(repo_path: Path, branch: str) -> None:
    subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=repo_path, check=True, capture_output=True,
    )


def _git_push(repo_path: Path, branch: str, repo_url: str, token: str) -> None:
    if repo_url.startswith("https://"):
        auth_url = repo_url.replace("https://", f"https://x-access-token:{token}@")
        subprocess.run(
            ["git", "remote", "set-url", "origin", auth_url],
            cwd=repo_path, capture_output=True,
        )
    subprocess.run(
        ["git", "push", "origin", branch],
        cwd=repo_path, check=True, capture_output=True,
    )


def _teardown_sandbox(state: MigrationState) -> None:
    """Stop the sandbox container / E2B sandbox at end of run."""
    import os
    backend = os.environ.get("SANDBOX_BACKEND", "local").lower()
    try:
        if backend == "docker":
            container_id = state.get("sandbox_container_id", "")
            if container_id:
                from agent_core.sandbox import DockerSandbox
                profile = load_profile(state.get("profile_name", "java_to_kotlin"))
                sb = DockerSandbox(
                    image=profile.sandbox_image,
                    repo_path=state.get("repo_path", "/tmp"),
                    container_id=container_id,
                )
                sb.close()
        elif backend == "e2b":
            sb_id = state.get("e2b_sandbox_id", "")
            if sb_id:
                from agent_core.sandbox import E2BSandbox
                E2BSandbox(sandbox_id=sb_id).close()
    except Exception as e:
        log.warning("Sandbox teardown error: %s", e)


def _generate_pr_body_llm(
    profile_name: str,
    applied_patches: list,
    gave_up_files: list,
    file_eval_records: list,
    cost: float,
    trace_url: str,
    user_pr_feedback: str,
    run_id: str,
) -> str:
    """Call LLM to write a narrative PR description. Falls back to template on error."""
    try:
        # Build per-file rules summary
        eval_by_path = {r["path"]: r for r in file_eval_records}
        file_rules_lines = []
        for p in applied_patches:
            rec = eval_by_path.get(p["path"], {})
            rules = ", ".join(rec.get("rules_applied", [])) or "general"
            file_rules_lines.append(f"- `{p['path']}` ({rules})")
        file_rules_list = "\n".join(file_rules_lines) or "(none)"

        # Build skipped detail
        skipped_lines = []
        for f in gave_up_files:
            rec = eval_by_path.get(f, {})
            attempts = rec.get("fix_attempts", "?")
            skipped_lines.append(f"- `{f}` (fix attempts: {attempts})")
        skipped_detail = "\n".join(skipped_lines) or "(none)"

        # Collect critic escalations and revisions
        critic_flags = [
            f"- `{r['path']}`: {r.get('critic_verdict','')} — {r.get('critic_notes','')[:200]}"
            for r in file_eval_records
            if r.get("critic_verdict") in ("revise", "escalate")
        ]
        critic_notes = "\n".join(critic_flags) or "(none)"

        prompt = _PR_BODY_LLM_PROMPT.format(
            profile_name=profile_name,
            files_ok=len(applied_patches),
            file_rules_list=file_rules_list,
            files_skipped=len(gave_up_files),
            skipped_detail=skipped_detail,
            critic_notes=critic_notes,
            user_pr_feedback=user_pr_feedback or "(none)",
            cost=cost,
            trace_url=trace_url or "(not available)",
        )

        budget = get_run_budget(run_id)
        body, _ = complete_with_cost(prompt, system=_PR_BODY_LLM_SYSTEM, tier=Tier.MID,
                                     max_tokens=1024, budget=budget)
        return body.strip()
    except Exception as exc:
        log.warning("LLM PR body generation failed (%s) — using fallback template", exc)
        file_list = "\n".join(f"- `{p['path']}`" for p in applied_patches) or "(none)"
        skipped_list = "\n".join(f"- `{f}`" for f in gave_up_files) or "(none)"
        return _PR_BODY_FALLBACK.format(
            profile_name=profile_name,
            files_ok=len(applied_patches),
            files_skipped=len(gave_up_files),
            cost=cost,
            file_list=file_list,
            skipped_list=skipped_list,
            trace_url=trace_url or "(not available)",
        )


def _open_github_pr(
    repo_url: str,
    branch: str,
    profile_name: str,
    applied_patches: list,
    gave_up_files: list,
    cost: float,
    github_token: str,
    pr_body: str = "",
) -> str:
    from github import Github

    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", repo_url)
    if not m:
        return f"(could not parse repo from {repo_url})"
    repo_slug = m.group(1)

    g = Github(github_token)
    gh_repo = g.get_repo(repo_slug)

    pr_obj = gh_repo.create_pull(
        title=f"chore: {profile_name} migration ({len(applied_patches)} files)",
        body=pr_body,
        head=branch,
        base=gh_repo.default_branch,
    )
    return pr_obj.html_url
