"""pr node — push the migration branch and open a GitHub PR.

HITL gate 3: interrupt_before=["pr"] in graph.compile(). The human sees
applied_patches + gave_up_files in the state, reviews, then resumes.
This node runs once on resume and opens the PR.
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
import uuid
from pathlib import Path

from migration.profiles import load_profile
from migration.state import MigrationState

log = logging.getLogger(__name__)

_PR_BODY = """\
## Automated `{profile_name}` migration

Generated by **code-migration-agent**.

| | |
|---|---|
| Profile | `{profile_name}` |
| Files migrated | {files_ok} |
| Files skipped | {files_skipped} |
| Estimated cost | ${cost:.4f} USD |

### Files changed
{file_list}

### Skipped (manual attention needed)
{skipped_list}

---
*Trace: {trace_url}*
"""


def pr(state: MigrationState) -> MigrationState:
    """Push the branch and open a GitHub PR.

    Called once after HITL gate 3 approves (the static interrupt fires
    *before* this node; on resume this runs to completion).
    """
    applied_patches = state.get("applied_patches", [])
    gave_up_files = state.get("gave_up_files", [])
    profile_name = state.get("profile_name", "")
    repo_path = Path(state.get("repo_path", ""))
    repo_url = state.get("repo_url", "")

    if not applied_patches:
        log.warning("No patches to commit — nothing to push")
        return {**state, "pr_url": "(no changes)", "langfuse_trace_url": ""}

    github_token = os.environ.get("GITHUB_TOKEN", "")
    if not github_token:
        log.warning("GITHUB_TOKEN not set — skipping push/PR")
        return {**state, "pr_url": "(no GITHUB_TOKEN)", "langfuse_trace_url": ""}

    # Create and push the migration branch
    branch = f"migration/{profile_name}/{uuid.uuid4().hex[:8]}"
    _git_checkout_branch(repo_path, branch)

    # All commits were made by next_file; we just need to push the branch
    _git_push(repo_path, branch, repo_url, github_token)

    # Open PR via PyGithub
    pr_url = _open_github_pr(
        repo_url=repo_url,
        branch=branch,
        profile_name=profile_name,
        applied_patches=applied_patches,
        gave_up_files=gave_up_files,
        cost=state.get("total_cost_usd", 0.0),
        github_token=github_token,
    )

    log.info("PR opened: %s", pr_url)
    _teardown_sandbox(state)
    return {**state, "pr_url": pr_url, "langfuse_trace_url": ""}


def _git_checkout_branch(repo_path: Path, branch: str) -> None:
    subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=repo_path, check=True, capture_output=True,
    )


def _git_push(repo_path: Path, branch: str, repo_url: str, token: str) -> None:
    if repo_url.startswith("https://"):
        auth_url = repo_url.replace("https://", f"https://x-access-token:{token}@")
        subprocess.run(
            ["git", "remote", "set-url", "origin", auth_url],
            cwd=repo_path, capture_output=True,
        )
    subprocess.run(
        ["git", "push", "origin", branch],
        cwd=repo_path, check=True, capture_output=True,
    )


def _teardown_sandbox(state: MigrationState) -> None:
    """Stop the sandbox container / E2B sandbox at end of run."""
    import os
    backend = os.environ.get("SANDBOX_BACKEND", "local").lower()
    try:
        if backend == "docker":
            container_id = state.get("sandbox_container_id", "")
            if container_id:
                from agent_core.sandbox import DockerSandbox
                profile = load_profile(state.get("profile_name", "java_to_kotlin"))
                sb = DockerSandbox(
                    image=profile.sandbox_image,
                    repo_path=state.get("repo_path", "/tmp"),
                    container_id=container_id,
                )
                sb.close()
        elif backend == "e2b":
            sb_id = state.get("e2b_sandbox_id", "")
            if sb_id:
                from agent_core.sandbox import E2BSandbox
                E2BSandbox(sandbox_id=sb_id).close()
    except Exception as e:
        log.warning("Sandbox teardown error: %s", e)


def _open_github_pr(
    repo_url: str,
    branch: str,
    profile_name: str,
    applied_patches: list,
    gave_up_files: list,
    cost: float,
    github_token: str,
) -> str:
    from github import Github

    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", repo_url)
    if not m:
        return f"(could not parse repo from {repo_url})"
    repo_slug = m.group(1)

    g = Github(github_token)
    gh_repo = g.get_repo(repo_slug)

    file_list = "\n".join(f"- `{p['path']}`" for p in applied_patches) or "(none)"
    skipped_list = "\n".join(f"- `{f}`" for f in gave_up_files) or "(none)"

    body = _PR_BODY.format(
        profile_name=profile_name,
        files_ok=len(applied_patches),
        files_skipped=len(gave_up_files),
        cost=cost,
        file_list=file_list,
        skipped_list=skipped_list,
        trace_url="(Langfuse trace — Phase 4)",
    )

    pr_obj = gh_repo.create_pull(
        title=f"chore: {profile_name} migration ({len(applied_patches)} files)",
        body=body,
        head=branch,
        base=gh_repo.default_branch,
    )
    return pr_obj.html_url
